### ISSUE TITLE
Global setting for callout pointer (and page pointer) border

### ISSUE THREAD

**Issue by jacovandermolen** [trevorsandy/lpub3d#510] opened 2021-03-13 12:45 UTC
### Subject
Hi Trevor,

Now, I use a lot of Callouts and I almost always use a (white) pointer border, since the pointer line and arrowhead are often over the assembly images. When using a black pointer it is often necessary to set up a white border for the pointer to be able to see it clearly over black and other dark-colored parts.

Currently, you have to set this up every time and with every instance of a pointer.
It would be great if you can globally set up the attributes of the border for a pointer.
Something like this
`0 !LPUB CALLOUT POINTER_ATTRIBUTE GLOBAL BORDER 1 #ffffff 0.016 1 `

Thanks

### Environment  
Version of LPub3D - 2.4.2
Operating system - All  

### Solution

`GLOBAL` and `LOCAL` scope support has been added. The command syntax has also been updated while preserving support for the legacy command syntax.

Here is an example of the new syntax for the pointer border attribute:
`0 !LPUB CALLOUT POINTER_ATTRIBUTE GLOBAL BORDER SOLID COLOR #ffffff WIDTH 0.016`

...and for the pointer line attribute:
`0 !LPUB CALLOUT POINTER_ATTRIBUTE GLOBAL LINE SOLID COLOR #ffffff WIDTH 0.016` 

...and the optional pointer line command to suppress the pointer tip:
`HIDE_TIP TRUE`
The default `HIDE_TIP` state is `FALSE` so specifying `HIDE_TIP FALSE` is redundant and; therefore, not required.

When either the line or border command is specified for a specific pointer, the `ID <pointer occurrence number>` command must be present and the `LOCAL` or `GLOBAL` command must not be present. For `LOCAL` and `GLOBAL` scope, the `ID` command is ignored because the meta command settings will be applied across all pointer occurrences in the specified scope.

Lastly, for `PAGE` pointers which require a base position, the trailing `BASE_TOP|BASE_BOTTOM|BASE_LEFT|BASE_RIGHT` command remains unchanged.

Cheers,

**Comment by trevorsandy** [comment] 2021-03-13 12:57
Thank you for reporting this behaviour. I’ll take a look.

Could you provide a syntax example that shows the difference between what you are currently doing and what you would like to do ?

Cheers,

**Comment by jacovandermolen** [comment] 2021-03-13 15:12
Upon converting a submodel to a callout (with pointer) I have to right-click the pointer, choose Edit border attributes, click the Change button next to Color, click on the desired color, click OK, and another OK.
That is 6 clicks and action per instance of a pointer.

What I'd like is to be able to set the attributes of a pointer somewhere globally.

**Comment by trevorsandy** [comment] 2021-03-13 16:02
Understood. Thank you for the update. I’ll take a look.

Cheers,

**Comment by trevorsandy** [comment] 2021-03-15 08:30
Jaco, take a look at the latest DevOps build (r1). I’ve added global pointer settings. I don’t like the meta command syntax so I plan to do some cleanup before release. Of course the current syntax will continue to be supported.

Cheers,

**Comment by trevorsandy** [comment] 2021-03-18 19:12
Implemented.

Cheers,

**Comment by jacovandermolen** [comment] 2021-03-19 09:37
Great! Can I test? I see the latest DevOps build is 2620 (r1) from 4 days ago.
I guess this change is not yet in there?

**Comment by jacovandermolen** [comment] 2021-04-06 19:28
Do you set this up here?

![afbeelding](https://user-images.githubusercontent.com/32261647/113765980-3ab94c00-971d-11eb-9c1d-e46457df276a.png)

If I do this:
![afbeelding](https://user-images.githubusercontent.com/32261647/113766391-a3082d80-971d-11eb-99ad-cf42042430a5.png)

I expect this:

![afbeelding](https://user-images.githubusercontent.com/32261647/113766695-01351080-971e-11eb-87e2-ff405a94af78.png)

But I get this:

![afbeelding](https://user-images.githubusercontent.com/32261647/113766776-1f9b0c00-971e-11eb-8cba-63053da797f4.png)

Setting either line or border results in this meta
0 !LPUB CALLOUT POINTER_ATTRIBUTE GLOBAL LINE SOLID COLOR #ffffff WIDTH 0.016 HIDE_TIP FALSE

Navigating the pages, LPub crashes with a dump file.
[LPub3D.dmp.txt](https://github.com/trevorsandy/lpub3d/files/6267082/LPub3D.dmp.txt)

**Comment by DanieleBenedettelli** [comment] 2021-04-06 19:31
Hello.
Same topic, different request: is it possible to make the size of the arrow
parametric?
Keeping the proportions and setting the length, or defining triangle base
and height would be OK.

Thanks,
D

Il giorno mar 6 apr 2021 alle ore 21:28 Jaco van der Molen <
***@***.***> ha scritto:

**Comment by trevorsandy** [comment] 2021-04-06 21:49
Thank you for reporting this behaviour and providing the dump output.

> Do you set this up here?

Yes.

> But I get this:...

I must have broken or mistyped something. The generated command for border is obviously producing the output for line.

If you change `LINE` to `BORDER` in the generated command, you should see the expected behaviour. 

> is it possible to make the size of the arrow
parametric?

It is. But it will take a considerable amount of coding to add all the UI components needed to reliably bring this fine-grained control to the user. Anyway, I’ll take a look.

Cheers

**Comment by jacovandermolen** [comment] 2021-04-07 18:00
OK, I found out changing the meta to
`0 !LPUB CALLOUT POINTER_ATTRIBUTE GLOBAL BORDER COLOR #ffffff WIDTH 0.016`
works like it should.

Need more change to `0 !LPUB CALLOUT POINTER_ATTRIBUTE GLOBAL LINE SOLID COLOR #ffffff WIDTH 0.016 HIDE_TIP FALSE` then replace LINE by BORDER ;-)

**Comment by trevorsandy** [comment] 2021-04-07 19:38
Corrected. 

As suspected, I mistyped  and updated the callout divider pointer, versus the intended pointer.

> Setting either line or border results in this meta
`0 !LPUB CALLOUT POINTER_ATTRIBUTE GLOBAL LINE SOLID COLOR #ffffff WIDTH 0.016 HIDE_TIP FALSE`

With the last DevOps build, you should not see the `HIDE_TIP FALSE` command. `HIDE_TIP` will only be generated if it is `TRUE`. This behaviour must have been generated with an earlier build ?

Anyway, I just checked in this fix so you can download the DevOps build, assuming no breaks, to check the behaviour. 

If you are able to reproduce the navigation crash you mentioned above, can you post an updated dump file with the latest DevOps build ? I did not generate a symbols (pdb) file for the previous builds so the old dump file is pretty useless. 

Cheers,

**Comment by jacovandermolen** [comment] 2021-04-07 20:10
I’ll check!

**Comment by jacovandermolen** [comment] 2021-04-08 07:04
OK, this is fixed!
Correct meta is written and no crash navigating pages.

**Comment by trevorsandy** [comment] 2021-04-13 15:33
>  Same topic, different request: is it possible to make the size of the arrow
parametric?
Keeping the proportions and setting the length, or defining triangle base
and height would be OK.

This behaviour has been implemented. See #528

Cheers,

**Comment by jacovandermolen** [comment] 2021-04-15 08:01
One more little thing,,,
The line for the pointer should be behind the arrow
![afbeelding](https://user-images.githubusercontent.com/32261647/114833410-d73fb600-9dcf-11eb-89af-046edb4a0a20.png)

**Comment by trevorsandy** [comment] 2021-04-16 18:43
Thank you for reporting this. I’ve checked in a DevOps update that treats this behaviour. Note however that the current DevOps build 2703 (r41) is unstable. There are Native renderer and LDraw Editor items yet to be treated. 

Cheers,

**Comment by jacovandermolen** [comment] 2021-04-17 08:52
OK, so I have noticed.

**Comment by trevorsandy** [comment] 2021-04-26 20:51
This behaviour implementation has been completed. 

Closing this ticket.

Cheers,

**Closed by trevorsandy** 2021-04-26 20:51 UTC
Labels: enhancement:hammer_and_wrench:
