### ISSUE TITLE
Callout crashed LPub3D

### ISSUE THREAD

**Issue by snakebyte73** [trevorsandy/lpub3d#458] opened 2020-10-06 13:22 UTC
### Subject
After upgrading to LPub3D-2.4.0.0.1990_20201003.exe it crashes every time i try to make a callout.
I then tried to downgrade through the previous versions.
When i got to LPub3D-2.3.13.0.1511_20190910 it startet working again.
I tried to upgrade one version again just to test and i startet crashing again.
after downgrading again to LPub3D-2.3.13.0.1511_20190910 i stopped crashing again.
Examplefile added. ignore the first 3 pages and go to Frint_01.ldr and convert to callout.

### Environment
* Version of LPub3D - see Help->About LPub3D
LPub3D-2.4.0.0.1990_20201003
* Operating system - OS Name, Processor Architecture (x86,x86_64)
Windows 10 x64

### Configuration
[Note: Provide details and content below as needed with appropriate redactions. To produce the Windows registry extract for an installed distribution, go to the command console and enter the command line shown. The extract file will be placed on your desktop.]
* LPub3D installation path
  C:\Program Files\LPub3D

* Application data path
  %USERPROFILE%\AppData\Local\LPUb3D Software\LPub3D\

* Registry Extract
  - Windows (installed): `reg export "HKEY_CURRENT_USER\Software\LPub3D Software" %USERPROFILE%\Desktop\LPub3D_Hive.reg`

* Renderer configuration files
  - `[Application data path]/ldv/ldvExport.ini`
  - `[Application data path]/3rdParty/ldglite-1.3/config/ldglite.ini`
  - `[Application data path]/3rdParty/ldview-4.4/config/ldview.ini`
  - `[Application data path]/3rdParty/ldview-4.4/config/ldviewPOV.ini`
  - `[Application data path]/3rdParty/lpub3d_trace_cui-3.8/config/povray.conf`
  - `[Application data path]/3rdParty/lpub3d_trace_cui-3.8/config/povray.ini`

### Logs
* Application Log: `[Application data path]/logs/LPub3DLog.txt`
* Renderer Log: `[LDraw model path]/stdout-ldglite`
* Renderer Log: `[LDraw model path]/stdout-povray`
* Renderer Log: `[LDraw model path]/stderr-ldglite`
* Renderer Log: `[LDraw model path]/stderr-povray`
[LPub3D_Files.zip](https://github.com/trevorsandy/lpub3d/files/5334062/LPub3D_Files.zip)

### Screenshots
* Configuration->Preferences->General
* Configuration->Preferences->Rendering
* Configuration->Preferences->Publishing
* Configuration->Preferences->Logging
* Configuration->Preferences->Other

### Steps to reproduce
See description

### Expected behaviour
Callout created

### Actual behaviour
program craches

### Workaround
Downgrade program to LPub3D-2.3.13.0.1511_20190910 

### Solution suggestion
Share your opinion on how to achieve the expected behaviour

**Comment by trevorsandy** [comment] 2020-10-06 15:32
Can you describe a bit more what steps you are taking to produce the abnormal end ?

I loaded the sample file you provided and selected 'Convert to callout' at context menu of the first step of submodel _front_01.ldr_. 

This was my result without any unexpected behaviour:

![image](https://user-images.githubusercontent.com/13388970/95223412-d4994e00-07f9-11eb-87df-00dc904d8223.png)

Cheers,

**Comment by snakebyte73** [comment] 2020-10-06 15:50
Hi Trevor
That is the exact step that makes it crash on my computer
unless i downgrade to the version described.

**Comment by snakebyte73** [comment] 2020-10-06 15:52
![billede](https://user-images.githubusercontent.com/38093610/95225970-b2ed9600-07fc-11eb-9b16-a90ae8a3faa1.png)

**Comment by trevorsandy** [comment] 2020-10-06 16:04
1 Try downloading and extracting a [protable distribution](https://github.com/trevorsandy/lpub3d/releases/download/v2.4.0/LPub3D_x86_64-2.4.0.0.1990_20201003.zip) to a location independent of your main LPub3D installation. 
2. Setup your model file in a new location along with your pictures etc...
3. Launch the portable instance of LPub3D by double clicking the executable.
4. Set your LDraw library path and any other custom paths as necessary...
5. Open the model file, navigate to the first step of front_01.ldr.
6. Select 'Convert to Callout' from the context menu and confirm the behaviour. 
7. If you expereince an abnormal end, try the capture a screenshot of hte message. Bundle it and the LPub3D log and attach it to this ticket.

Cheers,

**Comment by snakebyte73** [comment] 2020-10-06 17:23
Hi Trevor.
I set the preferred renderer to LDView and changed almost nothing else.
I copied the file i included in the zip file earlier and it crashed the same place.
It does not come up with a message. It just crashes.
I have included the LPub3DLog as requested
[LPub3DLog.zip](https://github.com/trevorsandy/lpub3d/files/5335552/LPub3DLog.zip)

**Comment by snakebyte73** [comment] 2020-10-06 17:24
![billede](https://user-images.githubusercontent.com/38093610/95238226-7ecca200-0809-11eb-8073-4161e5102483.png)
![billede](https://user-images.githubusercontent.com/38093610/95238243-84c28300-0809-11eb-96d7-d711feee0319.png)

**Comment by trevorsandy** [comment] 2020-10-06 17:48
For me with LDView [normal setting] set as renderer:

![Screenshot - 06_10_2020 , 19_40_00](https://user-images.githubusercontent.com/13388970/95240137-467a9300-080c-11eb-8a5f-9889e8c2a6ff.png)

![Screenshot - 06_10_2020 , 19_40_18](https://user-images.githubusercontent.com/13388970/95240178-53978200-080c-11eb-9d95-c1e834d821df.png)

![Screenshot - 06_10_2020 , 19_42_19](https://user-images.githubusercontent.com/13388970/95240215-5eeaad80-080c-11eb-8b5e-ae980fe7473a.png)

![Screenshot - 06_10_2020 , 19_46_50](https://user-images.githubusercontent.com/13388970/95240467-bdb02700-080c-11eb-9d66-93878c47282d.png)

I just know where to look because I'm not seeing any anomaly. Nevertheless, I'll keep looking.

Cheers,

**Comment by trevorsandy** [comment] 2020-10-06 18:25
Ok - I got it to abnormal end with highlight current step turned on. This is encouraging.

Cheers,

**Comment by snakebyte73** [comment] 2020-10-06 19:09
Strange that it only uccors after version LPub3D-2.3.13.0.1511_20190910 ??
at least on my computer :D

**Comment by trevorsandy** [comment] 2020-10-12 05:09
Corrected. The update will be in 2.4.1.

![Screenshot - 12_10_2020 , 07_07_08](https://user-images.githubusercontent.com/13388970/95707436-d62f9f80-0c59-11eb-9aba-86d94ea77cbe.png)

Cheers,

**Closed by trevorsandy** 2020-10-12 05:09 UTC
Labels: bug:bomb:

**Comment by snakebyte73** [comment] 2021-01-14 07:38
When will LPub3D 2.4.1 bee released?
Latest version i could find is LPub3D-2.4.0.0.1990_20201003.exe

**Comment by trevorsandy** [comment] 2021-01-14 08:02
Version 2.4.1 will be officially released when I believe it is reasonably stable. 

Until then, you are welcome to evaluate the [Continuous DevOps Build](https://github.com/trevorsandy/lpub3d-ci/releases/tag/continuous). 

Sharing any unexpected behaviour you encounter will be appreciated and will serve to further stabilise LPub3D towards official release.  

Cheers,

**Comment by snakebyte73** [comment] 2021-01-14 10:08
Hi Trevor
Thanks for the fast reply.
Is there any way to subscribe to when it is released ??

**Comment by trevorsandy** [comment] 2021-01-14 11:34
You can watch this GitHub repository or install the last release (2.4.0) and enable check for updates in Preferences.

Cheers,
