### ISSUE TITLE
Bill of Materials - Part Element Annotation not visible

### ISSUE THREAD

**Issue by forelockmocs** [trevorsandy/lpub3d#513] opened 2021-03-17 07:28 UTC
### Subject
In version 2.4.1 the part element annotation is not visible (it worked fine in 2.3.13.133). I got all boxes ticked that have to be ticked:
![image](https://user-images.githubusercontent.com/62996120/111429098-c7618300-86f8-11eb-9bed-1c9a3aa563ef.png)

This is my testversion for a Bill of Materials:
![image](https://user-images.githubusercontent.com/62996120/111429260-0c85b500-86f9-11eb-841c-99c9fd72ea90.png)

The part numbers are not visible. I then choose "Local" to try something else. I then got the message "LEGO Part Element file was not found". What am I doing wrong?

### Environment
--
* Version 2.4.1
* Win10
 
### Configuration
[Note: Provide details and content below   as needed with appropriate redactions. To produce the Windows registry   extract for an installed distribution, go to the command console and enter   the command line shown. The extract file will be placed on your desktop.]
* LPub3D installation path
C:\Program Files\LPub3D
* Application data path
C:\Users\ron_h\AppData\Local\LPub3D   Software\LPub3D
* Registry Extract
HKEY_CURRENT_USER\SOFTWARE\LPub3D   Software\LPub3D
* Renderer configuration files
C:\Users\ron_h\AppData\Local\LPub3D   Software\LPub3D\ldv\ldvExport.ini`
C:\Users\ron_h\AppData\Local\LPub3D   Software\LPub3D\3rdParty\ldglite-1.3\config\ldglite.ini`
C:\Users\ron_h\AppData\Local\LPub3D   Software\LPub3D\3rdParty\ldview-4.4\config\ldview.ini`
C:\Users\ron_h\AppData\Local\LPub3D   Software\LPub3D\3rdParty\ldview-4.4\config\ldviewPOV.ini`
C:\Users\ron_h\AppData\Local\LPub3D   Software\LPub3D\3rdParty\lpub3d_trace_cui-3.8\config\povray.conf`
C:\Users\ron_h\AppData\Local\LPub3D   Software\LPub3D\3rdParty\lpub3d_trace_cui-3.8\config\povray.ini`
 
### Logs
C:\Users\ron_h\AppData\Local\LPub3D   Software\LPub3D\logs\LPub3DLog.txt`
D:\Lego_Instructions\Lennart\Porsche_911\digital_model\stderr-ldglite
D:\Lego_Instructions\Lennart\Porsche_911\digital_model\stderr-povray

### Screenshots
* Configuration->Preferences->General
* Configuration->Preferences->Rendering
* Configuration->Preferences->Publishing
* Configuration->Preferences->Logging
* Configuration->Preferences->Other

### Steps to reproduce
This is my BOM setup code:
0 !LPUB BOM   ANNOTATION CABLE GLOBAL TRUE
0 !LPUB BOM ANNOTATION DISPLAY GLOBAL   TRUE
0 !LPUB BOM ANNOTATION ELEMENT GLOBAL   TRUE
0 !LPUB BOM ANNOTATION EXTENDED GLOBAL   TRUE
0 !LPUB BOM ANNOTATION FIXED_ANNOTATIONS   GLOBAL TRUE
0 !LPUB BOM ANNOTATION HOSE GLOBAL TRUE
0 !LPUB BOM ANNOTATION PANEL GLOBAL TRUE
0 !LPUB BOM ANNOTATION USE_FREE_FORM   GLOBAL TRUE
0 !LPUB BOM ANNOTATION   USE_TITLE_AND_FREE_FORM GLOBAL TRUE
0 !LPUB BOM BACKGROUND GLOBAL TRANSPARENT
0 !LPUB BOM BORDER GLOBAL NONE 0 MARGINS   0.050 0.050
0 !LPUB BOM CIRCLE_STYLE SIZE GLOBAL   0.1500 0.1500
0 !LPUB BOM CONSTRAIN GLOBAL WIDTH   11.6000
0 !LPUB BOM MODEL_SCALE 0.9000
0 !LPUB BOM PART MARGINS GLOBAL 0.0500   0.0500
0 !LPUB BOM PART_ELEMENTS DISPLAY GLOBAL   TRUE
0 !LPUB BOM PART_ELEMENTS   LOCAL_LEGO_ELEMENTS_FILE GLOBAL FALSE
0 !LPUB BOM SORT_ORDER PRIMARY GLOBAL   "Part Color"
0 !LPUB BOM SORT_ORDER PRIMARY_DIRECTION   GLOBAL "Ascending"
0 !LPUB BOM SORT_ORDER SECONDARY GLOBAL   "Part Size"
0 !LPUB BOM SORT_ORDER TERTIARY GLOBAL   "Part Element"
0 !LPUB BOM SQUARE_STYLE FONT GLOBAL   "Arial,22,-1,5,50,0,0,0,0,0,Standaard"
0 !LPUB BOM SQUARE_STYLE SIZE GLOBAL   0.1500 0.1500

### Expected behaviour
I would like to see the part numbers in the BOM

### Actual behaviour
It won't show

### Workaround
None

### Solution suggestion
The part number should be visible

**Comment by trevorsandy** [comment] 2021-03-18 09:42
Thank you for reporting this behaviour. I'll take a look.

Cheers,

**Comment by trevorsandy** [comment] 2021-03-28 20:43
Corrected,

Cheers,

**Comment by trevorsandy** [comment] 2021-03-28 21:19
Use these settings

```
0 !LPUB BOM ANNOTATION EXTENDED GLOBAL TRUE
0 !LPUB BOM PART_ELEMENTS DISPLAY GLOBAL TRUE
0 !LPUB BOM ANNOTATION DISPLAY GLOBAL TRUE
0 !LPUB PLI ANNOTATION DISPLAY GLOBAL TRUE
```

Cheers,

**Comment by trevorsandy** [comment] 2021-03-28 21:38
### Solution suggestion
I can't reproduce the behaviour you are describing. For me the meta command list you provided behaves as expected. Try backing up and deleting your annotation files. The application will use the hard coded defaults and will prompt to download the element codes if not annotation files are detected locally.

Cheers,

**Comment by trevorsandy** [comment] 2021-03-29 07:00
### Update

> The application will use the hard coded defaults and will prompt to download the element codes if no annotation files are detected locally.

I forgot to mention that the format of the annotation files did change since 2.3.13 so the latest version of LPub3D is likely not detecting your old files. You should however receive message prompts as such accordingly. The new behaviour (since 2.3.13) will first look locally for the annotation file before using the hard coded defaults. If local files are present, they must include the required regular expression statement in the header to allow LPub3D to correctly read the data.

As I mentioned above, if you rename/delete your old local annotation files, LPub3D will use the hard coded defaults and download the elements file accordingly. With the exception of the Bricklink  (LEGO) elements file, you can generate new local files from LPub3D by triggering the edit action for the respective file from the configuration menu. If the file does not exist locally, LPub3D will generate it using the hard coded defaults and notify you on success or failure. Like this you can update the generated local file with your custom entries as needed. 

Cheers,

**Comment by trevorsandy** [comment] 2021-03-31 01:32
I will close this ticket. If you continue to experience the reported behaviour, please reopen.

Cheers,

**Closed by trevorsandy** 2021-03-31 01:32 UTC
Labels: Issue:bell:
