### ISSUE TITLE
High contrast and Automate Edge lines do not work on certain systems

### ISSUE THREAD

**Issue by jacovandermolen** [trevorsandy/lpub3d#740] opened 2023-09-06 11:32 UTC
### Subject
High contrast, Automate Edge lines do not work on certain systems

Related to https://github.com/trevorsandy/lpub3d/issues/731
I know I said to let this problem go, but perhaps with this info and screenshots you can look in to it once more?
I find it hard to accept that it does work fine on one laptop and not on 2 other PC's I use.

### Environment
LPub3D_x86_64-2.4.7.75.3551_20230905
Windows 10

### Configuration
Through LDConfig set edge lines of black parts to white:

0                              // LEGOID  26 - Black
0 !COLOUR Black                                                 CODE   0   VALUE #1B2A34   EDGE #FFFFFF

[LDConfig.ldr.txt](https://github.com/trevorsandy/lpub3d/files/12536553/LDConfig.ldr.txt)

I have set up LPub config to use that specific LDConfig

![LPub3DPrefs](https://github.com/trevorsandy/lpub3d/assets/32261647/fb425040-b515-48f5-8b59-eac8b60255ef)

### Screenshots
LPub3D_x86_64-2.4.7.75.3551_20230905 shows me this:

![Render](https://github.com/trevorsandy/lpub3d/assets/32261647/bef02f87-4093-405d-9a7f-df7034064feb)

Though in setup I have automate edges on:

![ProjectGlobalsSetup](https://github.com/trevorsandy/lpub3d/assets/32261647/300bc303-9cb7-46ed-91c5-d352f31699c9)

![PartsListGlobalsSetup](https://github.com/trevorsandy/lpub3d/assets/32261647/68c58188-156d-44e2-9364-57b806f71936)

(studstyle High contast does work ;-)

### Steps to reproduce
Load model car.ldr = fresh model with no LPub commands whatsoever. Clear caches, etc.
Loads like screenshot above.
In LPub3D_x86_64-2.4.6.84.3426_20230314 the 3D preview _does_ show white edges on the black bricks!?

![3DPreviewOK](https://github.com/trevorsandy/lpub3d/assets/32261647/b39df340-e0f8-467d-829e-ad964b493167)

### Expected behaviour
I expect the edge line of black parts to be white.
(and other dark color automate a light edge color for that matter)

### Actual behaviour
Edge lines in the assembly and PLI are not white but still standard greyish.

### Workaround
Use LPub3D 2.4.5 or earlier ;-)

### Solution suggestion
No idea. I work with LPub and LDraw programs on multiple laptops and computers and on only one laptop the problem does _not_ occur. I now have 2 Windows PC's that do not render as I expect, though it was working just fine before.
The edge line for black part in LDCad (the editor) are white, set up through mentioned LDConfig.

Can this have anything to do with the hardware? Graphics card, monitor, ...?
Or the way I have multiple local LPub instances on my harddrives, but all with their own unique local ini and setup?

**Comment by trevorsandy** [comment] 2023-09-06 12:26
Thank you for reporting this behaviour. 

> I have set up LPub config to use that specific LDConfig
I expect the edge line of black parts to be white.

It looks like there is a misunderstanding. You cannot have both Automate Edge Colors and High Contrast Stud Style selected at the same time. If you want white edge lines uncheck Automate Edge Color.

There is a control in the Project Global Setup that prompts you to select one option or the other. It looks like I did not add this control to all the locations where these settings are present.

![AutomateEdgeColours_01](https://github.com/trevorsandy/lpub3d/assets/13388970/a706192f-a7ad-4277-8d93-daae84627fad)

As you can see in the WhatsThis help - Automat Edge Colors will 'generate' the edge color based on the specified Settings... This most certainly means black parts will not have pure white edge lines. Moreover, the specified LDConfig file edge colors will not be respected.

You can also controls which high-contrast color options are enabled through the Settings... dialogue.

![AutomateEdgeColours_02](https://github.com/trevorsandy/lpub3d/assets/13388970/265c9abe-da4b-47a3-ba3c-f457edf99f62)

For example, if you desire white edge lines for black parts (without using custom LDConfig settings) but do not want dark stud cylinders, simply select high-contrast stud style (6) and uncheck Stud Cylinder Color.

Do not hesitate to let me know if you are experiencing other behaviour not addressed by this post.

Cheers,

**Closed** 2023-09-06 12:27 UTC
Labels: user configuration

**Comment by trevorsandy** [comment] 2023-09-06 12:37
I took a look at the Parts List Global Setup and the control when selecting Automate Edge Color with High Contrast Stud Style already selected is in place. The message as indicated in the screenshot above should display.

When the situation is reversed - i.e. Automate Edge Colors is already checked and you select High Contrast Stud Style - you will see this message.

![AutomateEdgeColours_03](https://github.com/trevorsandy/lpub3d/assets/13388970/1e5a2cf2-491a-43c6-bcf5-c4c416709cd6)

Cheers,

**Comment by jacovandermolen** [comment] 2023-09-06 14:31
Right. Then my expectations and thoughts are not correct.

Somehow, I decided to delete the LPub3D.ini file and start all over again.
Surprise: render with high contrast works like I expect, but only in Perspective mode. Orthographic still looks not OK to me.

I have more findings but will post those later.

**Comment by trevorsandy** [comment] 2023-09-06 15:35
> I have more findings but will post those later.

Very well.

Cheers,

**Comment by jacovandermolen** [comment] 2023-09-07 06:58
So, I tested on my laptop at home and the rendering is OK in both orthographic and perspective mode. Nice white edges on black parts and black edges on white parts and dark on all other colors.

In perspective mode on my PC's at work, the lines are _very_ thin, the antialiasing looks bad and the contrast is not good. The 3D preview renders fine.

I will post 2 screenshots here to compare.

Long story short: what I need and always want for my instructions is white edges on black parts and black edges on white parts and all other colors for that matter, LEGO style studs, sharp lines with smooth antialiasing. This can now only be achieved in perspective mode in the newer versions of LPub. I had to delete the LPub.ini file for that to work.

What I am looking for is this to work in orthographic mode on all machines I work on, for which I have no clue on how to get that to work, whatever combination of settings I use.

**Comment by jacovandermolen** [comment] 2023-09-07 07:08
Compare version 2.4.7.x (left) and 2.4.5 (right). This is the same model file with the same settings.
As you can see the images that 2.4.7 produces has less quality and no black edges on parts with other color than black.
This is on 2 PC's at work with fresh local installations of LPub3D with ini files deleted and clean fresh LDraw files with no LPub meta commands.

My laptop at home produces the same image with 2.4.7 and 2.4.5...

![Difference245vs247ortho](https://github.com/trevorsandy/lpub3d/assets/32261647/3bea1932-0f36-4d46-a4fb-3a5062fa37af)

![Difference245vs247orthoZoomed](https://github.com/trevorsandy/lpub3d/assets/32261647/5ad10803-6aa1-45ea-9272-55b99145580c)

**Comment by trevorsandy** [comment] 2023-09-07 09:37
Thank you for sharing these details.

> In orthographic mode on my PC's at work, the lines are very thin, the antialiasing looks bad and the contrast is not good. The 3D preview renders fine.

To be sure I well understand. The v2.4.7 renders on your work PC are unexpected only for the orthographic view ? Further, both the v2.4.7 work PC render and 3DView do not display edge line color and quality as expected for high contrast stud style ?

If my understanding is correct, then I'm inclined to think the problem is in rendering edge lines in general. I do recall changing the settings code for this so I'll take a look.

The challenge for me is that rendered and 3D images for v2.4.5 and v2.4.7 are both as expected - like on your home PC.

Cheers,

**Comment by jacovandermolen** [comment] 2023-09-07 10:20
Yes, that is correct.
Thanks a lot again for your patience and effort!
It means a lot to me too to get this right ;-)

So far 2.4.7 is working good with buildmods and such.

**Comment by trevorsandy** [comment] 2023-09-08 09:25
I looked over the code and could not find any default settings that would yield the behaviour you are seeing on your work PC. Furthermore, I tested 2.4.7r75 on 12-year-old hardware running Windows 10 and the results were as expected.

As I cannot reproduce this behaviour, at this point, the way forward seems to be to shoot-in-the-dark and hope to hit something.

I imagine I could produce some personal builds, which you could try on your work PC, that exclude changes I suspect may cause the behaviour you are seeing. However, rolling back old commits is not so easy and may cause unexpected collateral impacts. 

Can you say something about the specs of your work PC ? For example, what version of OpenGL are you using ?

In LPub3D, you can see your OpenGL specs at Visual Editor->About Visual Editor - by LeoCAD... Here is an example:

![DifferentRenderQuality_01](https://github.com/trevorsandy/lpub3d/assets/13388970/86a9bf2b-ff10-4387-90cb-e0e16799218b)

Cheers,

**Comment by jacovandermolen** [comment] 2023-09-08 09:44
OK, I see.
At work I seem to have either OpenGL 4.6.0 build 30.0.101.1340 on one PC and ...1339 on the other PC
Different Graphic cards.

**PC1**
![image](https://github.com/trevorsandy/lpub3d/assets/32261647/534ce7ac-25ca-42a7-9efa-3390f578dc1b)
**PC2**
![image](https://github.com/trevorsandy/lpub3d/assets/32261647/0ee61046-ecd4-455b-8acc-ea9085fec8e5)

I have to check at home.

For now I think we can definitely close this case since it seems too much work and effort to find a needle in a haystack.
I can work on models and instructions on any machine, but I'll have to live with generating the PDF (or PNG's) on my laptop at home ;-)

Again, thanks for looking into it.
I will continue to test other features and give you feedback.

**Comment by jacovandermolen** [comment] 2023-09-08 15:19
Laoptop at home:

![image](https://github.com/trevorsandy/lpub3d/assets/32261647/88357c89-316a-4d7a-a787-7425697f08c4)

**Comment by technicbasics** [comment] 2024-11-04 16:27
> 
> For example, if you desire white edge lines for black parts (without using custom LDConfig settings) but do not want dark stud cylinders, simply select high-contrast stud style (6) and uncheck Stud Cylinder Color.
> 
> Do not hesitate to let me know if you are experiencing other behaviour not addressed by this post.
> 
> Cheers,

Hello Trevor
That's exactly what I wanted to try now, but somehow it doesn't work. No matter in which menu I deactivate the setting (uncheck Stud Cylinder Color), it is immediately active again. I am currently using the mobile unzipped version 2.4.8r0 running as administrator.

**Comment by trevorsandy** [comment] 2024-11-04 17:50
Hi Johann - Thank you for reporting this behaviour. I'll take a look.

Cheers,

**Comment by technicbasics** [comment] 2024-11-04 18:21
Hi
I have run a few tests.
When the project is opened, the setting is deactivated in all settings. As soon as the first page is selected, the setting is reset and stays that way.
Here is a short video...
[Stud Highlight.zip](https://github.com/user-attachments/files/17622336/Stud.Highlight.zip)

https://github.com/user-attachments/assets/52cc973b-2dce-41dd-a0d3-04de3fce525c

**Comment by trevorsandy** [comment] 2024-11-05 04:02
I've corrected this behaviour and created a new ticket - see #781.

Cheers,
