### ISSUE TITLE
LPub crashes when taking manual action on page elements

### ISSUE THREAD

**Issue by ErfinderDesRades** [trevorsandy/lpub3d#499] opened 2021-01-21 15:45 UTC
Hello everybody,

first of all I would like to say thank you to Trevor Sandy for the real great job. I love this application and would really really like to use it for creating instruction manuals for my MOCs, but unfortunately I experience a crash issue nearly every time I take a manual action on an element what ist placed on a page.

In Detail:

- I have installed version LPub3D-2.4.0.310.2530_20210121 
- OS is Win10 64
- machine Lenovo Thinkpad P52, 32 GB RAM, graphics adapter Nvidia Quadro P2000

The application starts without any problems and also changing settings and so on works fine. As soon as I try to move, for example an assembly, by drag and drop the application shows the spinner for about 5 seconds and then crashes, mostly without any message. Only one time (out of about 100 tries with different settings) there was a message:

"Run: Exception Access violation - no RTTI data! has been thrown."

I attached the latest log-file, hoping this will help.

As this behaviour is independent from the model file I use, I suppose it has something to do with a general issue concerning the installation environment.

So some help would be really highly appreciated.

Greetings from Bremen in Germany
[LPub3DLog.txt](https://github.com/trevorsandy/lpub3d/files/5850405/LPub3DLog.txt)

**Comment by trevorsandy** [comment] 2021-01-21 18:09
Thank you for reporting this behaviour.

DevOps builds can sometimes be unstable and the latest build is because I’m in the middle of adding a new capability. 

Secondly, it is not a good practice to use an installed distribution (.exe) of a DevOps build for the reason stated above. Installed builds are created largely to verify the install build script has no failures with new content. The better practice is to use a portable distro (.zip) which does not require installation. Simply download the archive file and extract it. The executable is located in the extracted subfolder and will launch the app when clicked. All associated application files (log, config,  libraries etc...) are contained in the extracted location.

Having said all that, reading the log file you provided does not give any indication for the abnormal end. I would advise to use a portable build and let me know if you are having the same unexpected behaviour. Alternatively, it would be interesting to know if you are also seeing the this behaviour with previous official release - e.g. 2.3.13 or 2.4.0.

Cheers,

**Comment by ErfinderDesRades** [comment] 2021-01-21 19:20
Thanks for your quick response.

Indeed I've experienced the same behaviour with the mentioned official releases. But I will try to use the prtable version as soon as possible and sure I will report the result.

Have a nice evening.

**Comment by ErfinderDesRades** [comment] 2021-01-21 20:42
Could'nt wait to test. But unfortunately I experienced the same behaviour. I used the zip-versions of 2.4.0.0, 2.3.13 and even 2.3.12.

Always the same. 

As a matter of interest I tried the latest official version on an old machine and it worked slowly (because of the poor hardware) but without crashes. So I suppose it has something to do with the software environment on the new machine.
Are there any concerning requirements which I might not fulfill? Any necessary frameworks or something like this?

Regards

**Comment by ErfinderDesRades** [comment] 2021-02-07 15:14
Hello everybody,

as this issue didn't let me in peace, I tested a lot of different adjustments on my laptop. Finally I succeeded. LPub runs nearly faultless when using the following compatibility settings (unfortunately I do'nt know the english name of the settings, just look for DPI settings):

<img width="616" alt="2021-02-07 14_30_44-" src="https://user-images.githubusercontent.com/77791504/107149207-9f436f00-6957-11eb-928f-d618fdb37183.png">

Just for explanation: I use a 4K monitor.

 After setting up the start behaviour in this way, you can manually move parts and assemblys without crashes.

During the testing of different adjustments I recohnized another interesting issue. For the display settings I use a scaling factor of 150 %:

<img width="356" alt="2021-02-07 16_11_26-Einstellungen" src="https://user-images.githubusercontent.com/77791504/107150666-38c24f00-695f-11eb-8265-7efcf0a05ff1.png">

 This is obviously a setting which doesn't work for LPub. As soon as I reduce this factor to a value less than 150%, LPub works. If I increase this factor to 150 % or above, LPub crashes when manually moving any objects.

Did anybody experience the same issues?

Regards

**Comment by trevorsandy** [comment] 2021-02-10 16:35
Thank you for reporting this update. 

Indeed, I have seen unexpected behaviour related to DPI scaling. Have a look at #292. However, the abnormal end (crash) is new.  I'll take a look.

Cheers,

**Comment by trevorsandy** [comment] 2021-03-31 01:34
I will close this ticket. If you continue to experience the reported behaviour, please reopen.

Cheers,

**Closed by trevorsandy** 2021-03-31 01:34 UTC
Labels: Development :construction:
