### ISSUE TITLE
Messed up and weird rendering

### ISSUE THREAD

**Issue by jacovandermolen** [trevorsandy/lpub3d#518] opened 2021-04-02 07:44 UTC
### Subject
Messed up and weird rendering

### Environment
* Version of LPub3D 2.4.2
* Windows 10, 64-bit

### Configuration
Portable installation
Native renderer, orthographic
Hi contrast studs

### Steps to reproduce
Certain steps and PLI images render very weird.
Totally random.

### Expected behaviour
Render should be good?

### Actual behaviour
![car_150_DPI_page_2](https://user-images.githubusercontent.com/32261647/113394070-e79b6e00-9397-11eb-9312-b86c4d944810.png)

### Workaround
Refresh cache / Reload

### Solution suggestion
Fix the renderer?

**Comment by trevorsandy** [comment] 2021-04-02 09:05
Thank you for reporting this behaviour. 

Interesting, I seems like I should have seen this during my tests. To confirm, this is only occurring with orthographic projection ? Could you take a screenshot of the ‘about 3DViewer’ (last action of the 3DViewer menu) dialogue. 

I’ll take a look.

Cheers,

**Comment by jacovandermolen** [comment] 2021-04-02 09:41
So far I only saw this happen with ortho projection (since I always and only use that) and with contrast studs on.

![afbeelding](https://user-images.githubusercontent.com/32261647/113404362-5680c300-93a8-11eb-8bf0-3388a5f82654.png)

**Comment by jacovandermolen** [comment] 2021-04-02 09:43
This is with contrast studs off and complete new and fresh model, no cache, etc.
See PLI step 5 and 6 (door and tile) render messed up.

![afbeelding](https://user-images.githubusercontent.com/32261647/113404530-96e04100-93a8-11eb-8229-2d1ae22281f9.png)

**Comment by jacovandermolen** [comment] 2021-04-02 09:45
After refreshing, the red 1x1 brick and the other door in step 5 are messed up, but the tile in step 6 is OK?

![afbeelding](https://user-images.githubusercontent.com/32261647/113404679-d444ce80-93a8-11eb-9f96-8d9271ce41d7.png)

**Comment by jacovandermolen** [comment] 2021-04-02 09:48
Seems to be random. No assembly images render wrong, but now only the PLI images of bricks seem to be affected.
Switching to Perspective rendering has this too. Step 6 black 1x4 plate:
![afbeelding](https://user-images.githubusercontent.com/32261647/113404926-44535480-93a9-11eb-83f4-3b4056fcdeeb.png)

**Comment by trevorsandy** [comment] 2021-04-02 10:51
Many thanks. 

One more request. Can you post a shot of the first three 3DViewer Preferences tabs - Rendering, Views and General ?

Cheers,

**Comment by jacovandermolen** [comment] 2021-04-02 11:46
![afbeelding](https://user-images.githubusercontent.com/32261647/113412900-bb90e480-93b9-11eb-8e47-dbd3818c5fd0.png)
![afbeelding](https://user-images.githubusercontent.com/32261647/113412913-c51a4c80-93b9-11eb-96c9-f4de0cbf211e.png)
![afbeelding](https://user-images.githubusercontent.com/32261647/113412933-d400ff00-93b9-11eb-9812-6ae146a37540.png)

**Comment by trevorsandy** [comment] 2021-04-02 12:04
I cannot reproduce this behaviour. I've tried on a fresh portable x86_64 distro of v2.4.2 r0 and on my latest DevOps instances. 

Here's what I'm getting with the portable distro:

LPub3D working folder and log for Orthographic Projection with High Contrast Stud Style
[Car_Ortho_High_Contrast.zip](https://github.com/trevorsandy/lpub3d/files/6249398/Car_Ortho_High_Contrast.zip)

LPub3D working folder and log for Perspective Projection with High Contrast Stud Style
[Car_Pers_High_Contrast.zip](https://github.com/trevorsandy/lpub3d/files/6249399/Car_Pers_High_Contrast.zip)

Portable distribution INI file
[LPub3D.ini.zip](https://github.com/trevorsandy/lpub3d/files/6249403/LPub3D.ini.zip)

Perhaps you can clean/redownload your portable distro, load again the car model and compare your INI and logs with mine.

Cheers,

**Comment by trevorsandy** [comment] 2021-04-06 03:37
Please try the latest continuous release. I will close this ticket. If you continue to experience the reported behaviour, please reopen.

Cheers,

**Closed by trevorsandy** 2021-04-06 03:37 UTC
Labels: cannot reproduce:warning:

**Comment by jacovandermolen** [comment] 2021-04-06 06:24
On my laptop at home no trouble so far. I will let you know when it occurs again.

**Comment by jacovandermolen** [comment] 2022-06-16 06:04
Hi Trevor,
Now that it seems you are working on LPub3D again, I'd like to re-open this issue, since it still happens in 2.4.4.4.2675_20220612.
I have done some testing again, and it seems only to occur when the Visual Editor is active.

Scenario:

1. Start LPub3D and activate the Visual Editor (and in my case I have the Command Editor open too, no other dialogs like Timeline and such)
2. Open an new LDraw file (no cache images yet) and start rendering and navigate through some pages
3. Now, totally random some parts in PLI and even CSI are completely messed up, like I posted here
4. Clearing cache and re-rendering again, other parts or assembly images go wrong
5. Adding a BOM a few random parts are weird, refreshing and re-rendering some other parts may go wrong.

Closing LPub, clearing the caches again and restart without the Visual Editor active, all is just fine!

I hope this information is useful for fixing this?
You may contact me if you want to do some more testing.
Thanks!

**Comment by trevorsandy** [comment] 2022-07-03 08:08
Hi Jaco,

I continue to not be able to reproduce or experience this behavour - after following the instructions you provided. 

My default configuration is to display both the visual and command editors. With the exception of 'Stud Style' setting, my visual editor preferences are the same as those you present. 

In testing my latest Build Mod fixes, I've manually rendered the entire 40252LPub243x.mpd model file you provided - with both the visual and command editor displayed as shown below - and none of the the images were malformed.

Perhaps you can confirm that your LDraw archive libraries are not the source of this behaviour. Are you updating your libraries after installing LPub3D - e.g. importing custom parts ? 

![Screenshot - 03_07_2022 , 10_07_07](https://user-images.githubusercontent.com/13388970/177030997-c07ffacf-487e-4d85-96c6-6ee83f968b4d.png)

You can take an advanced look at v2.4.5 with the latest [DevOps build](https://github.com/trevorsandy/lpub3d-ci/releases/tag/continuous).

Let me know if your checks continue to produce this unexpected behaviour.

Cheers,

**Comment by trevorsandy** [comment] 2022-07-04 04:03
Hi Jaco, 

Update: It just occurred to me that this behaviour may be caused by  the visual editor part file cache being, or becoming, corrupt. This is quite unlikely but not impossible. To reset the cache for a portable distribution, simply navigate to the location of your LPub3D executable and delete the cache folder. A new one will be created when LPub3D is restarted. For installed distributions, the cache folder is under ...AppData\Local\LPub3D Software\LPub3D.

Cheers,

**Comment by jacovandermolen** [comment] 2022-07-04 07:10
Hi Trevor,

Good to hear from you again!
This indeed seems highly unlikely, because I have this problem with a fresh
portable distribution, without custom parts.
I will look into this and get back to you.

Jaco


Op ma 4 jul. 2022 om 06:03 schreef Trevor SANDY ***@***.***>:

**Comment by jacovandermolen** [comment] 2022-07-04 07:36
Following the link to de DevOps download I see version 2.4.3.138.2925 to be the latest?
![image](https://user-images.githubusercontent.com/32261647/177105165-04ada050-80d6-4a9b-a4f9-226e1fe99fa8.png)

**Comment by trevorsandy** [comment] 2022-07-04 09:43
> Following the link to de DevOps download I see version 2.4.3.138.2925 to be the latest?

That's correct. You can see the revision number is quite high (138). The version is not 2.4.4 because I haven't yet pushed the version tag to GitHub. With the version tag, which is in place in my DevEnv, the revision would be something like 28 as you can see on the image I posted.

Cheers,

**Comment by jacovandermolen** [comment] 2022-07-04 10:32
Ah yes, OK. I see.
I will continue testing.
