### ISSUE TITLE
Callout produces arrow which can't be displayed

### ISSUE THREAD

**Issue by scumpy0815** [trevorsandy/lpub3d#360] opened 2019-10-14 16:44 UTC
### Subject
When I transform a subfile into a callout, the pointer is broken leading to no page:
0 !LPUB CALLOUT POINTER CENTER 0 nan nan 0 0 0 0 0 0 1
With that "nan nan" Lpub3d is not able to generate a page. If I delete the line, the page is shown, but I have to manually add an arrow to all my callouts.
I attached the original file and the file with callouts.

### Environment
* Version of LPub3D - v2.3.13 r36 (Release); but I've got that problem longer
* Operating system - Windows 10 1903, x64

### Configuration
[Note: Provide details and content below as needed with appropriate redactions. To produce the Windows registry extract for an installed distribution, go to the command console and enter the command line shown. The extract file will be placed on your desktop.]
* LPub3D installation path
C:\LDraw\Lpub3d

### Steps to reproduce
See description above.

### Expected behaviour
Generate callout with arrow.

### Actual behaviour
No arrow
[Callout.zip](https://github.com/trevorsandy/lpub3d/files/3725481/Callout.zip)

**Comment by trevorsandy** [comment] 2019-10-21 17:32
Thank you for reporting this behaviour.

I am not able to reproduce this behaviour with the latest [continuous build release](https://github.com/trevorsandy/lpub3d/releases/tag/continuous). 

Perhaps you could try remarking your header globals and unremarking each item one at a time to see if this behaviour is triggered by one of the global settings interacting with the specifics of your platform.

Here is what I'm seeing:

![Screenshot - 21_10_2019 , 19_06_03](https://user-images.githubusercontent.com/13388970/67228108-ee9b1e80-f438-11e9-9314-1dd3c949e7c9.png)
![Screenshot - 21_10_2019 , 19_06_22](https://user-images.githubusercontent.com/13388970/67228109-ee9b1e80-f438-11e9-9b89-e9b1894d7719.png)

I will be pleased to reopen this ticket if I am able to reproduce this behaviour so do not hesitate to add any new information.

Cheers,

**Comment by jensbruehl** [comment] 2019-11-26 18:27
I have the same problem and I think I found the key to reproduce this issue:

![image](https://user-images.githubusercontent.com/50247249/69661291-684ea980-1082-11ea-94ff-c5be941262e2.png)

Only when LDView Single Call is enabled, the pointer creates the NAN positions, when you convert a submodel to callout.

**Comment by technicbasics** [comment] 2019-11-27 07:42
Hi
have the same problem, but I have disabled "Use LDView Single Call".
The problem must be deepper in the file.
Maybe a certain sequence of commands.
If i find something, i will report.

**Comment by trevorsandy** [comment] 2019-11-28 15:23
Jens, thank you for the update. I'll take a look.

Cheers,

**Comment by technicbasics** [comment] 2020-08-27 16:11
It seems that the problem arises when many nested sub-models are inserted as callouts. From a certain complexity of the model, the error occurs from a certain position on every newly inserted callout.
I already have the second model where I can observe this effect, but the number of the callout from where the error occurs is different.

**Comment by trevorsandy** [comment] 2021-03-13 15:00
Closing this ticket. If you continue to experience this behaviour with the latest LPub3D release, do not hesitate to reopen.

Cheers,

**Closed by trevorsandy** 2021-03-13 15:00 UTC
Labels: cannot reproduce:warning:
