### ISSUE TITLE
ROTSTEP END is broken?

### ISSUE THREAD

**Issue by jacovandermolen** [trevorsandy/lpub3d#696] opened 2023-04-01 19:19 UTC
### Subject
ROTSTEP END seems not to be working

### Environment
* Version of LPub3D - 2.4.6.102.3444_20230331

### Steps to reproduce
See this file
[rotstep.ldr.txt](https://github.com/trevorsandy/lpub3d/files/11130404/rotstep.ldr.txt)

### Expected behaviour
After 0 ROTSTEP END the ROTSTEP should end

### Actual behaviour
ROTSTEP is applied to the next step after ROTSTEP too and then applied 2 steps after ROTSTEP END

### Workaround
None found

CORRECT
![rotstep_150_DPI_page_1_correct](https://user-images.githubusercontent.com/32261647/229310056-1757387f-5e7f-45af-9087-d845612a00cf.png)

INCORRECT
![rotstep_150_DPI_page_1_incorrect](https://user-images.githubusercontent.com/32261647/229310058-8110667a-3cd1-43b1-a3da-47e4b636fe27.png)

Please note too that the assembly images are different sizes

**Comment by trevorsandy** [comment] 2023-04-01 21:47
Thank you for reporting this behaviour.

I'll take a look.

Cheers,

**Comment by trevorsandy** [comment] 2023-04-02 08:05
> ROTSTEP END seems not to be working

At what version did you notice the change in behaviour ?

Cheers,

**Comment by jacovandermolen** [comment] 2023-04-02 10:11
Atleast in 2.4.6.102.3444, but some cont.build versions before that from last 2 weeks or so.
I also noticed that BuildMod in the first step on a multistep doesn't work anymore.
I believe we had that one tackeled?

**Comment by trevorsandy** [comment] 2023-04-02 10:40
Yep - Looks like the ROTSTEP END behaviour changed at #653.

I've checked in a correction so let me know if the behaviour is restored for you using the DevOps build ?

![RotateEnd](https://user-images.githubusercontent.com/13388970/229347897-88f98228-18f3-483c-88e5-be69aae46673.png)

> I also noticed that BuildMod in the first step on a multistep doesn't work anymore.

Perhaps I'm playing 'wack-a-mole' with BuildMods again. Anyway, I'll take a look.

Cheers,

**Comment by jacovandermolen** [comment] 2023-04-02 17:42
OK, 2.4.6.106.3448_20230402 did fix the ROTSTEP END problem, but now crashes on the last page that has the BOM

**Comment by trevorsandy** [comment] 2023-04-02 18:08
> OK, 2.4.6.106.3448_20230402 did fix the ROTSTEP END problem, but now crashes on the last page that has the BOM

Can you copy paste a command snippet that reproduces this behaviour ? For me the BOM is generated as expected.

![RotateEnd_01](https://user-images.githubusercontent.com/13388970/229370817-81132b84-5770-448a-beba-fbe2d8a93771.png)

Cheers,

**Comment by technicbasics** [comment] 2023-04-02 20:01
Hi Trevor
It looks like for me, that also the "0 ROTSTEP x y z REL" is also broken.
In my file that I have made available to you, from step 45 (page 14), no single ROTSTEP command works anymore.
But this concerns only the main model. In the submodels the ROTSTEPS are executed correctly.
Oh, I almost forgot... Version 2.4.6r106 DevOps

**Comment by trevorsandy** [comment] 2023-04-02 20:20
> It looks like for me, that also the "0 ROTSTEP x y z REL" is also broken.

Very well - I'll take another look.

There are lots of dependencies so it's good to have many eyes taking a look.

Cheers,

**Comment by trevorsandy** [comment] 2023-04-07 08:47
This behaviour has been corrected.

Cheers,

**Closed by trevorsandy** 2023-04-07 08:47 UTC
Labels: bug:bug:

**Comment by technicbasics** [comment] 2023-04-10 07:22
Works fine in 2.4.6r131 :-)
