### ISSUE TITLE
part 36841 missing in PLI and BOM

### ISSUE THREAD

**Issue by elex-at-github** [trevorsandy/lpub3d#494] opened 2020-12-27 15:16 UTC
### Subject
Problems rendering part 36841.dat:
Using LDView for rendering results in the correct render of the build step, but the part is missing in the Part list and in the bill of materials.
Using the native renderer results in only a bounding box in all three places.
Using LDGLite shows no problems.
I have not found similar problems with other parts.
The code of 36841.dat and its subparts is identical to the code at the parts library at ldraw.org
Stepping through the document with 'Previous page' and 'Next Page' can make the missing parts appear in the PLI and BOM, but it then still doesn't apear when exporting to PDF.

The error can be reproduced with the following:

0 Untitled
0 Name: 36841.ldr
0 Author: LDraw
0 Unofficial Model
0 ROTATION CENTER 0 0 0 1 "Custom"
0 ROTATION CONFIG 0 0
1 0 0 0 0 1 0 0 0 1 0 0 0 1 36841.dat
1 4 0 -24 0 1 0 0 0 1 0 0 0 1 3005.dat
0 STEP
1 15 20 0 0 1 0 0 0 1 0 0 0 1 36841.dat
0 STEP
1 14 40 0 0 1 0 0 0 1 0 0 0 1 36841.dat
0
0 STEP
0 !LPUB INSERT PAGE
0 !LPUB INSERT BOM
0

### Environment
* Version of LPub3D - 2.4.0 Revision 0 Build 1990
* Operating system - Windows 10 Home

**Comment by trevorsandy** [comment] 2021-01-13 08:16
Thank you for reporting this behaviour; however, I am not able to reproduce it on my instance. 

For me, the behaviour is as expected.

![Screenshot - 08_01_2021 , 06_00_46](https://user-images.githubusercontent.com/13388970/104424667-f84dfc00-557f-11eb-909c-f42cd017b78c.png)

Cheers,

**Comment by trevorsandy** [comment] 2021-03-13 14:22
Closing this ticket.

If you continue to experience this behaviour do not hesitate to reopen.

Cheers,

**Closed by trevorsandy** 2021-03-13 14:22 UTC
Labels: Issue:bell:, cannot reproduce:warning:
