### ISSUE TITLE
Invalid Library Version (SDL2) and failure to render CSI parts files

### ISSUE THREAD

**Issue by trdoolan** [trevorsandy/lpub3d#387] opened 2019-12-19 11:20 UTC
### Subject
Describe your issue here.
Tried updating to current release (2.3.13.105.1616_20191216) after previous install began crashing each time I would try resize PLI boxes (v2.3.13.75.1586_20191109). 
Now, current version reports attached errors (invalid library versions error appears at 25% of startup process, followed by csiParts error after loading LDR file, LDView CSI render failure, then failure to create CSI file (screencaps archived and attached)

### Environment
* Version of LPub3D - see Help->About LPub3D
v2.3.13.105.1616_20191216
* Operating system - OS Name, Processor Architecture (x86,x86_64)
MacOSX Mojave 10.14.6

### Configuration
[Note: Provide details and content below as needed with appropriate redactions. To produce the Windows registry extract for an installed distribution, go to the command console and enter the command line shown. The extract file will be placed on your desktop.]
* LPub3D installation path
  - macOS: `/Applications/LPub3D.app`

* Application data path
  - macOS: `~/Library/Application Support/LPub3D Software/LPub3D/`

* Registry Extract
  - macOS: ` ~/Library/Preferences/com.lpub3d-software.LPub3D.plist`
  
* Renderer configuration files
  - `[Application data path]/ldv/ldvExport.ini`
  - `[Application data path]/3rdParty/ldglite-1.3/config/ldglite.ini`
  - `[Application data path]/3rdParty/ldview-4.3/config/ldview.ini`
  - `[Application data path]/3rdParty/ldview-4.3/config/ldviewPOV.ini`
  - `[Application data path]/3rdParty/lpub3d_trace_cui-3.8/config/povray.conf`
  - `[Application data path]/3rdParty/lpub3d_trace_cui-3.8/config/povray.ini`
Files included in archive attachment

### Logs
* Application Log: `[Application data path]/logs/LPub3DLog.txt`
* Renderer Log: `[LDraw model path]/stdout-ldglite`
* Renderer Log: `[LDraw model path]/stdout-povray`
* Renderer Log: `[LDraw model path]/stderr-ldglite`
* Renderer Log: `[LDraw model path]/stderr-povray`
Not all of these logs were available. 
Included: stdout-ldview, stderr-ldview

### Screenshots
* Configuration->Preferences->General
* Configuration->Preferences->Rendering
* Configuration->Preferences->Publishing
* Configuration->Preferences->Logging
* Configuration->Preferences->Other

Note: size of this window on initial opening results in contents displayed overlapping, requiring manual resize. This behaviour is consistent across most secondary windows spawned by this application.

Screen caps in subfolder "Config Screenshots" in attached archive.

### Steps to reproduce
Tell me how to reproduce this issue.
Normal launch of application produces first error re: library SDL2 version.
Second error on loading of LDR file.
[LPub3D Issue Dec19.zip](https://github.com/trevorsandy/lpub3d/files/3983296/LPub3D.Issue.Dec19.zip)

Provide a sample mpd/ldr file that reproduces the problem.
Attached archive: Ghost v0.4.20.ldr

### Expected behaviour
Tell me what should happen
Normal operation, start of application, load file, render page and contents, change and edit normally without app crash.

### Actual behaviour
Tell me what happens instead
For current release version: 
1. Library version error
2. errors on load of LDR file as attached.

### Workaround
Share your work around if available

### Solution suggestion
Share your opinion on how to achieve the expected behaviour
Suspect that there are multiple concurrent issues at play. Versions of libraries may be in conflict, or have permission issues, as files appear to be where the error claims they're not expected. Have updated Brew, and installed libraries per Readme_macos.txt in install.

**Comment by trevorsandy** [comment] 2019-12-19 15:15
Thank you for reporting this behaviour. 

Indeed, you have described multiple items:

>  current version reports attached errors (invalid library versions error appears at 25% of startup process

This is likely because the macOS SDL2 library version on your system has changed from 2.0.9 to 2.0.10 and the version string compare is interpreting .9 to be greater than .10. This message is benign and can be ignored as the installed version of SDL2 actually exceeds the minimum required.

> csiParts error after loading LDR file, LDView CSI render failure, then failure to create CSI file 

All these messages source from a single point of failure. The render routine was not able to find the .ldr render input file (csiFile) at the specified full file path.

For example, in LPub3D.log, the following lines...

```
2019-12-18T22:18:15.719 ERROR "File csiParts does not exist!" 
2019-12-18T22:18:20.607 ERROR "LDView CSI render failed for /Users/troy/Google Drive/Lego/03. MOCs & MODs/0038. MOC-032 - SW - Ghost (Instruction Project)/Instruction Development/LPub3D/assem/design v0.4.20_1_ghost_1_superstructure_1_0_0_0_1_0_0_0_1_1_1753_150_DPI_1_0.007_23_45.png" 
2019-12-18T22:20:24.096 ERROR "Failed to create CSI file."
```

... starting with ‘File csiParts does not exist!’ states that...

`/Users/troy/Google Drive/Lego/03. MOCs & MODs/0038. MOC-032 - SW - Ghost (Instruction Project)/Instruction Development/LPub3D/tmp/design v0.4.20_1_ghost_1_superstructure_1_0_0_0_1_0_0_0_1_1_1753_150_DPI_1_0.007_23_45.ldr`

... was not found so the corresponding .png file render failed.

You can check in `/Users/troy/Google Drive/Lego/03. MOCs & MODs/0038. MOC-032 - SW - Ghost (Instruction Project)/Instruction Development/LPub3D/tmp` to confirm if the file exist and the naming is consistent with what is specified in the message.

Cheers,

**Comment by trdoolan** [comment] 2019-12-19 15:47
Hi Trevor,

Noted on the first error (SDL2 library) being innocuous. Cool.

Looked in the folder .../LPub3D/tmp/ and no file named as such exists. Is
there a way to force creation of this file?

Thanks,
Troy

**Comment by trevorsandy** [comment] 2019-12-19 16:11
Hello Troy,

> Noted on the first error (SDL2 library) being innocuous. Cool.

I will update the macOS library check in the next update.

> Looked in the folder .../LPub3D/tmp/ and no file named as such exists. Is there a way to force creation of this file?

No, however you can play around with the path naming (i.e. move the model file to the user root and remove any non alphanumeric characters from its subfile names) to see if this is the source of the unexpected behaviour. I’ll take a look myself shortly to confirm but if no .ldr render input file is being generated, it usually means the specified file path is causing the file creation to fail.

**Comment by trdoolan** [comment] 2019-12-20 02:53
Hi Trevor,

Thanks for the rapid replies... genuinely appreciate you being on top of
it.

I tried a different LDR file. Shortened the path and filenames by copying
and pasting, renaming, as follows:
Filename: Delta7B.ldr
Path: /users/troy/Desktop/test/

No existing LPub3D subfolder tree. Errors appeared as previous, except with
the name of the files being related to the one being used in the test.

These are being tested under an account with admin privileges, permissions
on the files and folders should enable open creation/edit of files.
Admittedly, my limited understanding of the mechanics of the internals of
how LPub3D and it's support libraries work, I'm wondering if perhaps it's
an issue with something like LibPNG or another of the libraries needed as
part of the rendering process?

I don't know if this is related or not, but when I opened a file that had
an existing set of tmp files from previously successful renders, the parts
in the first PLI box were shown not at the relative angles (Lat/Long and
FOV) set in the configuration, but were x-axis only (appearing level, flat,
viewed directly from the side). If I can find another example, I'll screen
cap it and send it through.

Cheers,
Troy

**Comment by trevorsandy** [comment] 2019-12-20 06:17
Hi Troy,

Very well. I’ll have some time today to take a look. 

> I'm wondering if perhaps it's an issue with something like LibPNG or another of the libraries needed as part of the rendering process?

I don’t think so; instead, considering your tests, I believe this behaviour is likely linked to the last update - [#385](https://github.com/trevorsandy/lpub3d/issues/385).

Using the original configuration, try switching your renderer to Native to see if your results are as expected. It could also be helpful to enable ‘Show load messages’ on the General tab of Preferences - ‘on message’ is a good option.

> I don't know if this is related or not, but when I opened a file that had
an existing set of tmp files from previously successful renders, the parts
in the first PLI box were shown not at the relative angles (Lat/Long and
FOV) set in the configuration, but were x-axis only (appearing level, flat,
viewed directly from the side). If I can find another example, I'll screen
cap it and send it through.

Could you archive and share the LPub3D folder used in this test ?  

Cheers,

**Comment by trevorsandy** [comment] 2019-12-20 07:34
UPD: This behaviour is indeed sourced from #385.  Reviewing the code, I found the bug, and some routines that should be refactored. Basically, the camera globe and FOV flags are ignored when ‘use multiple file single call’ is not enabled. This behaviour will be fixed shortly.

Cheers,

**Comment by trdoolan** [comment] 2019-12-20 09:28
Hi Trevor,

Using the original configuration, try switching your renderer to Native to
see if your results are as expected. It could also be helpful to enable
‘Show load messages’ on the General tab of Preferences - ‘on message’ is a
good option

Native render results are no different, I'm afraid. Preferences > General >
Messages "Options" : all check boxes ticked. Will try find a good test
option, archive results and send through.

 Cheers,
Troy


Cheers,

**Comment by trevorsandy** [comment] 2019-12-21 19:02
This behaviour has been corrected.

Cheers,

**Closed by trevorsandy** 2019-12-21 19:02 UTC
Labels: bug:bomb:
