### ISSUE TITLE
Assembly placement wrong in 2.3

### ISSUE THREAD

**Issue by Landcross** [trevorsandy/lpub3d#102] opened 2018-09-16 14:08 UTC
### Subject
I recently upgraded to LPub 2.3 whilst in the midst of working on a project. Not one of my brightest ideas. In any case, I noticed a difference in assembly placement. Take a look at the images below.

**Before:**
![knipsel2](https://user-images.githubusercontent.com/12005521/45597277-0698a700-b9ca-11e8-9ab1-6867c3972463.PNG)

**After:**
![knipsel](https://user-images.githubusercontent.com/12005521/45597280-0ac4c480-b9ca-11e8-87d7-01e4919155cc.PNG)

As you can see at the bottom of page, the assembly is cut off before the end of the page, while in the earlier version it didn't. Also note that the model seems to be moved downwards compared to the 'before' image (take a look at the top of the transparant Technic beams).

The after image is taken using LPub 2.3. The before image is taken using LPub 2.1 as I couldn't get an image from LPub 2.2 (portable copy) so I'm not sure if the problem already exists in 2.2 or not (I also can't remember which copy I was using before I upgraded).

### Environment
* Version of LPub3D: LPub 2.3
* Operating system: Windows 10 Pro x64

I can't share the file here in public, so if you want to take a look at the LDraw file I need to send it to you (Trevor) personally.

**Comment by Landcross** [comment] 2018-09-18 14:42
> There is also the new "Native" renderer (I believe set to default - I can't remember) based on the 3DViewer (LeoCAD) engine that does not use the traditional camera distance calculator, you must adjust the camera distance factor manually (generally for pages other than A4) in Project Globals.

I don't quite understand how camera distance could have anything to do with cutting the image at the wrong place? In any case I am not using the native renderer (at least, I have LDView selected in the preferences). But I am using a page size that is different from A4 (it is A4 + 1cm on all sides)... 

Then again, it wasn't a problem in previous versions of LPub3D so I would assume it shouldn't be in 2.3. Any changes in placement or positioning in newer versions would mean that I can't re-render past projects anymore, which I regularly do to fix errors and such.

**Comment by trevorsandy** [comment] 2018-09-18 17:03
Ok - well I haven't intentionally done anything with placement in 2.3 but the way camera angles are transferred to the render were changed and  could certainly affect the position and orientation of the rendered image. In 2.3, I am erroneously passing the default angles (23,45) to the renderer for all renderings. For images with ABS rotation transform, 0,0 should be passed instead. This error is corrected in #95.

**Comment by Landcross** [comment] 2018-09-18 19:29
My example images above do not use ABS rotation though. They are default (ROTSTEP END).

**Comment by trevorsandy** [comment] 2018-09-25 01:49
Without an example to test, I can suggest taking a look at your header/footer settings. The global values are under Page Setup.

![screenshot - 25_09_2018 03_47_43](https://user-images.githubusercontent.com/13388970/45988201-0ce7ec80-c076-11e8-9aa6-26cdd3dfc90e.png)

Cheers,

**Comment by Landcross** [comment] 2018-09-25 14:49
My header and footer are at default (0.3). But as you can see in the images in the first post, not only is the image moved (or wrongly positioned) on the page, the actual camera seems to have moved as well. The transparant Technic lift-arms are completely visible in the second image and there is less of the brown plates visible at the bottom. And that's the thing that 'worries' me the most: if I need to update and/or re-render old building instructions I don't want the assembly images looking any different than what I had with previous versions.

I hope I don't sound negative or angry; I really appreciate your hard work with LPub3D and I gladly help you solve this issue as much as I can :)

I did look at the logs you mentioned and I can see the render commands. I'm just not sure what use there is looking at those as I don't have anything from 2.2 to compare with...

As a side-question: do you have any ETA for 2.3.1? I suppose you want this issue fixed before releasing it?

**Comment by trevorsandy** [comment] 2018-09-26 10:48
After, rereading my last response, I noticed I actually forgot to say what I really intended to.

> I'm just not sure what use there is looking at those as I don't have anything from 2.2 to compare with...

As you know, LPub3D uses 3rd-party renderer applications to generate step illustrations. Unexpected behaviour regarding such will be sourced from one of two origins - the rendered image or its placement on the page, the latter being the responsibility of LPub3D.

Having said that, the commands being passed to the renderer, available in the log, can be independently run from your command console to manually produce the illustration image. This action can help rule out or implicate the renderer as the source of the malformed image. From this you can also determine If the parameters sent to the renderer are affecting the rendered image.

Of course, having the command line from the pervious version of LPub3D, which is technically simple to get, will immediately show any difference in the transferred parameters between that version and the version showing the unexpected behaviour but this is not the only reason to take a look at the command output in the application log.

Anyway, to get the command sent to the renderer, you can create a fake exe in place of the renderer, to capture the output from LPub3D that you would then pipe “>>” to an output “log” before sending it on to the actual renderer that must obviously be renamed also. A fake exe being a simple “batch” file renamed to the name of the renderer and having an exe extension.

Your batch file could have something like this to capture, export and pass on the command:

```
@ECHO OFF
REM capture renderer command
FOR /F "tokens=*" %%A IN ('TYPE CON') DO SET INPUT=%%A
REM now  you can pipe ‘INPUT’ to a log
“%INPUT%” >> renderer_log.txt
REM finally send it on its way to the renderer
“%INPUT%”
```

Cheers,

**Comment by Landcross** [comment] 2018-09-29 11:10
Hi Trevor. Today I wanted to capture the output from an older version of LPub3D, so I removed LPub 2.3 and installed 2.2.2. However the image quality (issue #98 ) remained exactly the same as I had in 2.3... I was kinda confused as during the de-installation I selected to remove everything.

So, I de-installed again and installed an older version 2.2.0 or 2.2.1 (can't remember). And image quality was still the same (it didn't match my locally installed copy of LDView). I thought I could select my own LDView instance in the preferences, but it's unchangeable and by default set to the copy included with LPub3D. It has nothing to do with this issue, but one of the reasons I installed an older version was because I need to render the final copy of some building instructions, which I now can't (in the quality I want)...

But regarding this issue, your batch file technique doesn't seem to work (or I'm doing something wrong). It doesn't create any output logfile. I did render the same page with 2.1 and 2.3. They are attached below. If you open both pdfs and then quickly swap between them you can clearly see how the camera has shifted. Also, by doing that I have the suspicion that there's nothing wrong (or changed) with the assembly placement in 2.3 like I said earlier but it's just the camera that's doing things different/wrong while LPub3D does not know/expect. If that makes sense...

Here are the pdfs:
[compare.zip](https://github.com/trevorsandy/lpub3d/files/2430578/compare.zip)

**Comment by trevorsandy** [comment] 2018-09-29 11:55
Merlijn - thanks for the update.

If I well understand your analysis, then the unexpected behaviour is sourced from the renderer. If you are using an instance of the renderer that previously rendered the image as expected, the parameters being sent to the renderers - including those in LDView.ini - have changed. You might focus particularly on the camera globe settings: camera angle (default is 0.01), latitude (default is 23), longitude (default is 45) and camera distance (dynamically calculated based on page size and other attributes). 

The significant change between 2.2.2 and 2.3.0 for the camera globe settings is, up to 2.2.2, the latitude, longitude defaults are applied to the CSI part list position matrix before the CSI list is forwarded to the renderer; therefore, the renderer command passes 0.0 for these settings. From 2.3.0, the position matrix is not rotated by the defaults, so the command does include these defaults - except if ROTSTEP is ABS, where the settings will remain 0.0. The camera angle passed to the renderer in all versions is the default 0.01. However, it this setting is different in the LDraw.ini file, there may be a conflict. I haven't really looked at how LDView handles this so I'm not sure. If the behaviour is FIFO then the passed setting will prevail, if it's LIFO then the LDView.ini setting will override the command line instance.

> I thought I could select my own LDView instance in the preferences, but it's unchangeable and by default set to the copy included with LPub3D.

You still can change the instance of LDView, I've just made it a bit less convenient to do so. I did not hide the path to the renderers in Preferences precisely to allow replacement if it must come to that - I've even enabled the paths there to be copy/pasted. Just copy the path to your Explorer window, open the location, rename the existing instance of LDView and add your instance, respecting the appropriate name and machine architecture (x86, x86_64).

Cheers,

**Comment by Landcross** [comment] 2018-10-06 12:08
Honestly, I'm out of ideas to try. Last couple of days I installed and uninstalled LPub3D like 20+ times, trying different versions (2.1, 2.2, 2.3), comparing, looking at logs etc. I have no idea where the problem comes from (though I think it doesn't help that I don't have a good understanding of how LPub3D works under the hood). The only thing I know for sure is that something changed between 2.2 and 2.3 causing the aforementioned rendering/placement issue.

I also loaded up models from the past and I can confirm that the issue is not limited to the single model displayed above. Page from the final product, rendered ~a year ago:
![image](https://user-images.githubusercontent.com/12005521/46571186-e2007100-c970-11e8-93a9-c4070fb49d40.png)

The same page, when I open it in 2.3.2:
![image](https://user-images.githubusercontent.com/12005521/46571193-f17fba00-c970-11e8-92e1-b7931bf3f19d.png)

Notice the model has 'shifted' to the left, but the cutoff of the image is at the same relative place thus creating that weird cutoff at the left side of the assembly image. The problem seems exactly the same as showed before, just on the horizontal axis instead of the vertical axis. One thing both examples have in common, is that the assembly model overflows the page. I checked pages that do not overflow and they seem perfectly the same between < 2.3 and 2.3.

I can share the models if you want, but again, not publicly.

**Comment by trevorsandy** [comment] 2018-10-06 21:51
> Honestly, I'm out of ideas to try. Last couple of days I installed and uninstalled LPub3D like 20+ times, trying different versions (2.1, 2.2, 2.3), comparing, looking at logs etc. I have no idea where the problem comes from (though I think it doesn't help that I don't have a good understanding of how LPub3D works under the hood). The only thing I know for sure is that something changed between 2.2 and 2.3 causing the aforementioned rendering/placement issue.

Sorry to hear that you are going through so much turmoil. I really don't think tracking down this behaviour is so complicated. Installing and uninstalling LPub3D is not the good 'rabbit hole' to check. Instead, i would focus my effort on the renderer!

To do this, I'd start with the rendered image - is it shifted or is LPub3D cropping what is otherwise the expected image ?

If the image is being produced 'shifted', I would then look at the command string - does the command string produce the same image on a stock installation of the renderer ?

From these two checks, you can determine either 1. The LPub3D-generated command has change and is producing the unexpected output or 2. LPub3D's instance of the LDView renderer is 'shifting' the rendered image without any command parameter - including those in the LDView.ini - instigating such behaviour.

At this point, I would advise to send me - by personal email - an example file that produces this behaviour - along with the LPub3D log and a sample of the actual rendered .png file along with the .pdf document showing the shifted image. With this, I could try on my end to make some progress with the advantage of knowing how the program works under the hool.

Cheers,

**Comment by trevorsandy** [comment] 2018-10-08 06:32
This behaviour was introduced by #88 where I moved application of the latitude/longitude camera angles to the renderers. Prior to this change, LPub3D statically applied 23 degrees latitude, 45 degrees longitude to all part position and transform matrices before passing the CSI to the renderer.

The 'down-shifted' (**After**) rendering is how LDView renders the image when it is also given the task of applying the camera angles. The (**Before**) rendering is the LPub3D result when LPub3D applies the camera angles.

### Solution
Revert to applying the camera angles in LPub3D as the default setting and add a flag to the Preferences tab allowing the option to pass the camera angles to the renderers.

**Closed** 2018-10-08 08:56 UTC
Labels: Change
