### ISSUE TITLE
Crash when creating or moving Callout pointer

### ISSUE THREAD

**Issue by DanieleBenedettelli** [trevorsandy/lpub3d#514] opened 2021-03-22 16:59 UTC
### Subject
As soon as I add a CALLOUT pointer, LPUB crashes.
If I ignore the dialog, I can still work on the file for a little while. If I keep moving the pointers, the program actually closes.

### Environment
LPub3D BETA 2.4.1.17.2636 (also happening with stable release 2.4.1 r0
Win 10 x64

### Logs
[LPub3DLog.txt](https://github.com/trevorsandy/lpub3d/files/6183942/LPub3DLog.txt)
Can't attach the .dmp file, but I have it.

### Screenshots
![callout_crash](https://user-images.githubusercontent.com/47357389/112028137-262f5e00-8b38-11eb-8067-07397fcc0c49.png)

**Comment by trevorsandy** [comment] 2021-03-28 21:51
Try the latest DebOps build. I am not able to reproduce this behaviour on my latest build.

Cheers,

**Comment by trevorsandy** [comment] 2021-03-29 07:07
### Update

After taking a look at your posted image, I do recall a scenario where the pointer caused an abnormal end when the base (i.e the Callout) was not completely within the page dimensions - likely due to a fault when calculating the pointer position. Let me know if the abend persists if the callout is within the page dimensions.

Cheers,

**Comment by trevorsandy** [comment] 2021-03-31 01:30
I will close this ticket. If you continue to experience the reported behaviour, please reopen.

Cheers,

**Closed by trevorsandy** 2021-03-31 01:30 UTC
Labels: Issue:bell:
