### ISSUE TITLE
Please provide contributing instructions

### ISSUE THREAD

**Issue by mardy** [trevorsandy/lpub3d#338] opened 2019-09-03 19:16 UTC
### Subject
The `builds/utilities/README.md` file contains useful instructions to build LPub3D packages, but as a developer I'd like to know what is the best way to work on the code. It's probably possible to just install the dependencies by hand and then run `qmake` to build the project -- but there isn't a document that explains how to get all the needed dependencies in place.

### Environment
Ubuntu 16.04

### Solution suggestion
Have a `CONTRIBUTING.md` file which has step-by-step instructions on how to install the dependencies and build (and run) LPub3D directly from a git checkout. Other useful information might be what Qt version must be supported.

**Comment by trevorsandy** [comment] 2019-09-04 06:27
Hello Mardy. Thank you for expressing your interest in contributing to the development and maintenance of LPub3D.

LPub3D build dependencies are clearly defined in `builds/utilities/README.md`. It looks like you are interested in configuring an IDE however. My IDE for Windows 10 outline follows. These requirements are generally the same for Unix environments except where applications do not exist for such environments - e.g. MSVS.

Outline of my IDE on Windows 10 (not exhaustive):

**OS Platform:**
- Windows 10
- WSL - Windows Subsystem for Linux (Ubuntu on Window)

**Development Platforms:**
- MSVS 2017
- MSVC SDKs 14, 15
- Qt 5.11.3 (MSVC_2015)
- Qt Creator/Qt Designer 4.7.2

**Tools:**
- Notepad++ 7.7.1
- Sublime Text 3.2.1
- GitKraken 6.1.4
- Git/7-Zip
- WinMerge (Windows only)
- NSIS (Windows only)
- Docker (Desktop for Windows 10)
- Docker Compose (Windows 10)
- Xming - Enable GUI on Docker builds (Windows only)
- Dropbox

**Setup**
As a developer, the best way to understand and setup the requirements for your IDE is to:

1. Review the Qt project (.pro) and project include (.pri) files located at `mainApp`, and dependent script(s) usually located at `builds/utilities`. LPub3D automatically builds it's third-party renderers (LDView, LDGLite, POV-Ray) from source at compile time. You can see the full build sequence and dependencies in the following scripts:
- Windows: `builds/utilities/CreateRenderers.bat`
- Unix: `builds/utilities/CreateRenderers.sh`

2. Review the build script and its dependent script(s) usually located at `builds/utilities` for your particular environment of interest. LPub3D builds are automated for cloud-based CI so all build dependencies are automatically downloaded by the scripts as needed. There should be no need to manually download anything. 

Build scripts are located at the following locations:
- Window: `builds/windows/ AutoBuild.cmd` (build and stage), `builds/windows/CreateExePkg.cmd` (NSIS packaging)
- macOS: `builds/macx/CreateDmg.sh` (build and package)
- Debian: `builds/macx/CreateDeb.sh` (build and package)
- Fedora: `builds/macx/CreateRpm.sh` (build and package)
- Arch: `builds/macx/CreatePkg.sh` (build and package)
- AppImage: Downloaded at build time (build and package)

**Repositories**
I develop LPub3D across 2 GitHub repositories. Both repositories connect to their respective CI environments (AppVeyor for Windows and Travis-CI for Unix) and "Continuous" build releases are available from each repository.
- [LPub3D-CI](https://github.com/trevorsandy/lpub3d-ci) is the "continuous integration and test" repository where all development activity is checked into and where pull requests should be created.
- [LPub3D](https://github.com/trevorsandy/lpub3d) is the "production" repository where additional Open Build Service (OBS) artifacts are created for each commit. This repository is the source for the officially released distributions of LPub3D.

I also maintain a repository for each of the LPub3D third-party renderers. You can follow the instructions at each of these repositories to setup their build environments if needed. They are:
- [LDView](https://github.com/trevorsandy/ldview)
- [LDGLite](https://github.com/trevorsandy/ldglite)
- [POV-Ray](https://github.com/trevorsandy/povray)

Shared assets (specific platform libraries, config files and the like) are stored as releases at a central repository for ease of maintenance purposes:
- [LPub3D_Libs](https://github.com/trevorsandy/lpub3d_libs/releases)

**Approach**
For building on Ubuntu, I would:
- Ensure Qt (at least v5.11.3) is installed
- Install Qt Creator (at least 4.7.2)
- Install GitKraken (6.4.1)
- Follow the steps outlined in `builds/utilities/README.md` for that platform substituting `lpub3d` with `lpub3d-ci` so you will be working from the development and test repository. This should bring you to the point where all dependent libraries and such are automatically installed and your source repository will be pointing to the LPub3D development and test remote.
- Launch Qt Creator and open the LPub3D project file (LPub3D.pro) located at the root of the repository.
- Open the LPub3D repository in GitKraken and confirm your remote is LPub3D-CI
- Confirm you can successfully compile LPub3D
- [Optional] LDView, and LDGLite are configured to be built with Qt Creator. Simply open the respective project file and you will be good to go. POV-Ray however, is not configured to be built with Qt Creator. you will have to follow the POV-Ray documentation to create a gcc compatible IDE - I use Eclipse and can share with you the very complicated setup details if you want.

This should be enough to get you started. We can discuss on this ticket any specifics you may encounter on your journey. When it is demonstrated that this ticket is of good maturity, I will move the content to `CONTRIBUTING.md`

Cheers,

**Closed by trevorsandy** 2019-09-04 06:27 UTC
Labels: [how to]:bulb:

**Comment by mardy** [comment] 2019-09-05 20:05
Hi Trevor, thanks for your extensive explanations!
  I still have some question: when you say "Follow the steps outlined in builds/utilities/README.md for that platform substituting lpub3d with lpub3d-ci" it's not clear to me which script I should use. I did the following:

    LPUB3d=lpub3d-ci ./builds/linux/CreateDeb.sh

This created a `debbuild` directory, where it started the build. What I find a bit strance, is that it seems that it downloaded the same files many times:

```
$ find debbuild/  -name *.zip
debbuild/SOURCES/lpub3dldrawunf.zip
debbuild/SOURCES/lpub3d-2.3.12.1469/lclib/resources/library.zip
debbuild/SOURCES/tenteparts.zip
debbuild/SOURCES/complete.zip
debbuild/SOURCES/vexiqparts.zip
debbuild/lpub3d-2.3.12.1469/lclib/resources/library.zip
debbuild/lpub3d-2.3.12.1469/mainApp/extras/lpub3dldrawunf.zip
debbuild/lpub3d-2.3.12.1469/mainApp/extras/tenteparts.zip
debbuild/lpub3d-2.3.12.1469/mainApp/extras/complete.zip
debbuild/lpub3d-2.3.12.1469/mainApp/extras/vexiqparts.zip
debbuild/lpub3d_linux_3rdparty/lpub3dldrawunf.zip
debbuild/lpub3d_linux_3rdparty/complete.zip
debbuild/complete.zip
```

You can see for example that there are four copies of `complete.zip`, but also most of the other archives have been downloaded more than once.
Anyway, the script seemed to be successful for quite a while, only near the end it gave an error. You can read the full log [here](https://paste.ubuntu.com/p/BRvrrvFg3P/).

I wonder, is this the right procedure, or did I misunderstand something? I didn't really want to build a `.deb` package, I just wanted to setup all the dependencies and then build the project with QtCreator (or just by running `qmake` from the command line). I see that it used Qt 5.5 which I have installed in the system, whereas I would have preferred to use Qt 5.12, which I have installed in my home.

**Comment by trevorsandy** [comment] 2019-09-06 00:07
Hello Mardy,

The asset download behaviour is as designed.

The build seems to be failing at `Error parsing time at /usr/lib/x86_64-linux-gnu/perl/5.22/Time/Piece.pm line 469.` which is not a part of the LPub3D build scripts.

Also, it looks like you are attempting to set the `LPUB3d` variable (versus the `LPUB3D` variable) before running CreateDeb.sh. Ubuntu `bash` shell is case sensitive.

To build directly the `LPub3D-ci` source, substitute `lpub3d` with `lpub3d-ci` in the outlined build steps - for example:

- [ ] 1. enter your user directory  
`$ cd ~/`
- [ ] 2. get `CreateDeb.sh` build and packaging script. [if you already have a cloned `LPub3D-ci` GitHub remote, then substitute  `trevorsandy` with your repository owner ID and be sure to update the script paths pointing to the default repository].
`$ wget https://raw.githubusercontent.com/trevorsandy/lpub3d-ci/master/builds/linux/CreateDeb.sh`
- [ ] 3. enable execute permissions and execute the build and package script  
`$ chmod +x CreateDeb.sh && ./CreateDeb.sh`

This should bring you to the point where all dependent libraries and such are automatically installed and your local source repository at `~/lpub3d-ci` will be pointing to the `LPub3D-ci` development and test remote.

Next, launch Qt Creator and open the `LPub3D-ci` project file (LPub3D-ci.pro) located at the root of the automatically cloned source repository at `~/lpub3d-ci`.

> I see that it used Qt 5.5 which I have installed in the system, whereas I would have preferred to use Qt 5.12, which I have installed in my home.

The build scripts will use the native instance of Qt. You can use `qtchooser` to set an alternative Qt version. However, if your aim is to use Qt Creator, simply create a toolkit with the version of Qt you desire and you’ll be good to go.

Cheers,
